In [6]:
import numpy
import random

import tensorflow as tf
import tflearn

import math

from tflearn.layers.core import input_data, fully_connected

from tflearn.layers.estimator import regression


In [ ]:
#For my Final Project I decided to try to teach an AI to play the game 2048. I had started this project a little in the past, so I just continued working on it for my Final Project
#To do this I tried to use a genetic algorthimn to optomize the weights of the neural network
#The main problem with this approach is that it's quite difficult to determine how well each model did because you can get a pretty good score by moving randomly
#Therefore the metrics I used to determine how well a model did were score, turns were the highest value tile was in a corner, and illegal moves predicted by the models
#After running my program for several generations the best score I got was 12444 with the highest tile being 1024. However, it didn't really seem to get much better
#The actual training part of the program is the next_generation function at the bottom of the file

In [198]:
def new_tiles(board):
    new_board = board.copy()
    
    open_indexes = []
    for i in range (4):
        for j in range(4):
             if board[i][j] == 0:
    
                 open_indexes.append(i)
                 open_indexes.append(j)
    open_indexes = numpy.reshape(open_indexes, (-1,2))
    num_open = len(open_indexes)

    rand1 = random.randint(0,num_open - 1)
    
    
    index1 = open_indexes[rand1]


    if (random.randint(0,9) == 0):
        value1 = 4
    else:
        value1 = 2
    

   
    new_board[index1[0]][index1[1]] = value1

    return(new_board)

In [9]:
def compare_boards(board1, board2):
    for i in range(4):
        for j in range(4):
            if (board1[i][j] != board2[i][j]):
                return False
    return True

In [10]:
def move_left(board,score):
    
    new_board = board.copy()
    
  
    for i in range(0,4):
        for j in range(1,4):
            
            
            if new_board[i][j-1] == new_board[i][j]:
                new_board[i][j-1] = new_board[i][j-1] *2
                score = score + new_board[i][j-1]
                new_board[i][j] = 0
                    
        
            
    
        
    for _ in range(4):
        initial_board = board.copy()
        for i in range(3,-1,-1):
            for j in range(3,0,-1):
                if new_board[i][j-1] == 0:
                    new_board[i][j-1] = new_board[i][j]
                    new_board[i][j] = 0
        if compare_boards(initial_board, new_board):
            return (new_board, score)
    return (new_board,score)
    

    

In [11]:
def move_right(board,score):
    
    new_board = board.copy()
    
    for i in range(3,-1,-1):
        for j in range(2,-1,-1):
            if new_board[i][j+1] == new_board[i][j]:
                new_board[i][j+1] = new_board[i][j+1] * 2
                score = score + new_board[i][j+1] 
                new_board[i][j] = 0
                

    for _ in range(4):
        initial_board = board.copy()
        for i in range(0,4):
            for j in range(0,3):
                if new_board[i][j+1] == 0:
                    new_board[i][j+1] = new_board[i][j]
                    new_board[i][j] = 0
        if compare_boards(initial_board, new_board):
            return (new_board, score)
    return (new_board,score)
    

In [12]:
def move_up(board,score):
    
    new_board = board.copy()
  
    for i in range(1,4):
        for j in range(0,4):
            if new_board[i-1][j] == new_board[i][j]:
                new_board[i-1][j] = new_board[i-1][j] * 2
                score = score + new_board[i-1][j] 
                new_board[i][j] = 0
        

    for _ in range(4):
        initial_board = board.copy()
        for i in range(3,0,-1):
            for j in range(3,-1,-1):
                if new_board[i-1][j] == 0:
                    new_board[i-1][j] = new_board[i][j]
                    new_board[i][j] = 0
        if compare_boards(initial_board, new_board):
            return (new_board, score)
    return (new_board,score)

In [13]:
def move_down(board,score):
    
    new_board = board.copy()
  
    for i in range(2,-1,-1):
        for j in range(3,-1,-1):
            if new_board[i+1][j] == new_board[i][j]:
                new_board[i+1][j] = new_board[i+1][j] * 2
                score = score + new_board[i+1][j] 
                new_board[i][j] = 0
        
    for _ in range(4):
        initial_board = board.copy()
        for i in range(0,3):
            for j in range(0,4):
                if new_board[i+1][j] == 0:
                    new_board[i+1][j] = new_board[i][j]
                    new_board[i][j] = 0
        if compare_boards(initial_board, new_board):
            return (new_board, score)
    return (new_board, score)

In [14]:
def game_over(board):
    
    game_state1 = move_left(board.copy(), 0)[0]
    game_state2 = move_right(board.copy(), 0)[0]
    game_state3 = move_up(board.copy(), 0)[0]
    game_state4 = move_down(board.copy(), 0)[0]
    
    if compare_boards (game_state1, game_state2):
        if compare_boards(game_state2, game_state3):
            if compare_boards(game_state3, game_state4):
                return True
    return False

In [15]:
game_board = numpy.zeros((4,4))
game_board = new_tiles(game_board)
score = 0
gameOver = False
while gameOver == False:
    
    gameOver = (game_over(game_board))
        
    print(game_board)
    print(score)
    inputString = input()
    if (inputString == "w"):
        outputs = move_up(game_board,score)
        game_board = outputs[0]
        score = outputs[1]
    elif (inputString == "a"):
        outputs = move_left(game_board,score)
        game_board = outputs[0]
        score = outputs[1]
    elif (inputString == "s"):
        outputs = move_down(game_board,score)
        game_board = outputs[0]
        score = outputs[1]
    elif (inputString == "d"):
        outputs = move_right(game_board,score)
        game_board = outputs[0]
        score = outputs[1]
        
    game_board = new_tiles(game_board)
   

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 2.]
 [0. 2. 0. 0.]]
0


KeyboardInterrupt: 

In [16]:
def translate_board(board):
    
    
            
    
    new_board = board.copy()
    
    largest_value = 0
    for i in range(4):
        for j in range(4):
            if new_board[i][j] > largest_value:
                largest_value = new_board[i][j]
                
    base2val = math.log(largest_value, 2)
            

    
    for i in range(4):
        for j in range(4):
            
            if new_board[i][j] > 0:
            
                num = math.log(new_board[i][j],2)
            else:
                num = 0
            new_board[i][j] = num / base2val
            
    return new_board



In [360]:
models = []
hidden_layers = []
networks = []
for i in range(100):   
    print(i)
    tf.reset_default_graph()
    network = input_data(shape=[None, 4, 4], name='input')
    network = fully_connected(network, 4, activation='sigmoid')
    random_values1 = numpy.zeros((16,4))
    for i in range(16):
        for j in range(4):
            value = float(random.randrange(-100, 100))/100
            random_values1[i][j] = value


    hidden_layer = network.W
    network = fully_connected(network, 4, activation='softmax')
    network = regression(network, optimizer='adam', learning_rate=1e-2, loss='mean_square', name='target')
    model = tflearn.DNN(network)

    random_values2 = numpy.zeros((4,4))
    for i in range(4):
        for j in range(4):
            value = float(random.randrange(-100, 100))/100
            random_values2[i][j] = value
        
    
    model.set_weights(network.W, random_values2)
    model.set_weights(hidden_layer, random_values1)
    models.append(model)
    networks.append(network.W)
    hidden_layers.append(hidden_layer)

    
#create initial population of random NN


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [19]:
def test_model(model):
    
    gameStates = []
    gameMoves = []
    scores = []
    total_badMoves = []
    total_turnsInCorner = []
    all_scores = []
    
    for i in range(10):
        
        game_board = numpy.zeros((4,4))
        game_board = new_tiles(game_board)
        score = 0
        game_states = []
        game_moves = []
        gameOver = False
        isRepeating = False

        badMoves = 0
        turnsInCorner = 0
        
        move = 0
        
        legal_moves = [0,1,2,3]

        while gameOver == False:
            
                
            gameOver = (game_over(game_board))
            
            

            #game_states.append(game_board.copy())
            
            #print(game_board.copy())

            if isRepeating == False:
                
                legal_moves = [0,1,2,3]
                game_states.append(game_board.copy())
                game_moves.append(move)

                translatedBoard = translate_board(game_board)
                prediction = (model.predict([translatedBoard]))[0]
                move = 0
                largest_value = 0
                for i in range(4):
                    if prediction[i] > largest_value:
                        move = i
                        largest_value = prediction[i]
            
            
            if (move > 3 or move < 0):

                move = random.randint(0,3)
                
           

            isRepeating = False

            if (move == 0):

                initial_board = game_board.copy()
                outputs = move_up(game_board,score)
                game_board = outputs[0]
                translated_board = translate_board(game_board)
                if translated_board[0][0] == 1:
                    turnsInCorner += 1
                elif translated_board[0][3] == 1:
                    turnsInCorner += 1
                elif translated_board[3][0] == 1:
                    turnsInCorner += 1
                elif translated_board[3][3] == 1:
                    turnsInCorner += 1
                score = outputs[1]
                isRepeating = (compare_boards(game_board, initial_board))


                if isRepeating:
                    #gameOver = True
                    legal_moves.remove(0)
                    badMoves += 1
                    translatedBoard = translate_board(game_board)
                    prediction = (model.predict([translatedBoard]))[0]
                    move = 1
                    largest_value = 0
                    for num in legal_moves:
                        if prediction[num] > largest_value:
                            move = num
                            largest_value = prediction[num]
                        
                    #move = random.randint(1,3)

            elif (move == 1):


                initial_board = game_board.copy()
                outputs = move_left(game_board,score)
                game_board = outputs[0]
                translated_board = translate_board(game_board)
                if translated_board[0][0] == 1:
                    turnsInCorner += 1
                elif translated_board[0][3] == 1:
                    turnsInCorner += 1
                elif translated_board[3][0] == 1:
                    turnsInCorner += 1
                elif translated_board[3][3] == 1:
                    turnsInCorner += 1
                score = outputs[1]
                isRepeating = (compare_boards(game_board, initial_board))


                if isRepeating:
                    #gameOver = True
                    legal_moves.remove(1)
                    badMoves += 1
                    translatedBoard = translate_board(game_board)
                    prediction = (model.predict([translatedBoard]))[0]
                    move = 0
                    largest_value = 0
                    for num in legal_moves:
                        if prediction[num] > largest_value:
                            move = num
                            largest_value = prediction[num]


            elif (move == 2):


                initial_board = game_board.copy()
                outputs = move_down(game_board,score)
                game_board = outputs[0]
                translated_board = translate_board(game_board)
                if translated_board[0][0] == 1:
                    turnsInCorner += 1
                elif translated_board[0][3] == 1:
                    turnsInCorner += 1
                elif translated_board[3][0] == 1:
                    turnsInCorner += 1
                elif translated_board[3][3] == 1:
                    turnsInCorner += 1
                score = outputs[1]
                isRepeating = (compare_boards(game_board, initial_board))


                if isRepeating:
                    #gameOver = True
                    legal_moves.remove(2)
                    badMoves += 1
                    translatedBoard = translate_board(game_board)
                    prediction = (model.predict([translatedBoard]))[0]
                    move = 0
                    largest_value = 0
                    for num in legal_moves:
                        if prediction[num] > largest_value:
                            move = num
                            largest_value = prediction[num]




            elif (move == 3):


                initial_board = game_board.copy()
                outputs = move_right(game_board,score)
                game_board = outputs[0]
                translated_board = translate_board(game_board)
                if translated_board[0][0] == 1:
                    turnsInCorner += 1
                elif translated_board[0][3] == 1:
                    turnsInCorner += 1
                elif translated_board[3][0] == 1:
                    turnsInCorner += 1
                elif translated_board[3][3] == 1:
                    turnsInCorner += 1
                score = outputs[1]
                isRepeating = (compare_boards(game_board, initial_board))


                if isRepeating:
                    #gameOver = True
                    legal_moves.remove(3)
                    badMoves += 1
                    translatedBoard = translate_board(game_board)
                    prediction = (model.predict([translatedBoard]))[0]
                    move = 0
                    largest_value = 0
                    for num in legal_moves:
                        if prediction[num] > largest_value:
                            move = num
                            largest_value = prediction[num]



            
            


            spotOpen = False
            for i in range (4):
                for j in range(4):
                    if game_board[i][j] == 0:
                        spotOpen = True
            if spotOpen and isRepeating == False:
                game_board = new_tiles(game_board)
                
            #if isRepeating:
             #   break;
                
        
        all_scores.append(score)
        gameStates.append(game_states)
        gameMoves.append(game_moves)
        scores.append(score)
        total_badMoves.append(badMoves)
        total_turnsInCorner.append(turnsInCorner) 

       # for i in range(len(gameStates[0])):
        #    print(gameStates[0][i])
    
      

    total_score = 0
    num_bad_moves = 0
    num_turns_in_corner = 0
    for i in range(10):
        total_score = total_score + scores[i]
        num_bad_moves = num_bad_moves + total_badMoves[i]
        num_turns_in_corner = num_turns_in_corner + total_turnsInCorner[i]
        
    return total_score, num_bad_moves, num_turns_in_corner, all_scores

    


In [1442]:
best_models[0].get_weights(best_networks[0])

array([[ 0.22, -0.32,  1.45, -0.9 ],
       [ 1.09, -1.82,  1.46,  0.37],
       [ 1.99,  1.82,  1.4 , -1.57],
       [-0.47, -0.54,  0.03,  1.55],
       [ 0.02, -1.28,  0.41,  1.71],
       [ 0.69,  1.04,  0.32,  1.16],
       [-1.68, -0.99,  1.36,  1.82],
       [ 1.84, -1.43,  1.03,  1.52]], dtype=float32)

In [352]:
def create_children(parent1, parent2, network1, network2, hiddenLayer1, hiddenLayer2):
    
    parent_weights1 = parent1.get_weights(network1)
    parent_weights2 = parent2.get_weights(network2)
    
    hidden_layer_weights1 = parent1.get_weights(hiddenLayer1)
    hidden_layer_weights2 = parent2.get_weights(hiddenLayer2)

    crossOverIndex = random.randint(0,64)
    tf.reset_default_graph()
    network = input_data(shape=[None, 4, 4], name='input')
    network = fully_connected(network, 4, activation='sigmoid')
    weights1 = numpy.zeros((16,4))
    for i in range(16):
        for j in range(4):
            
            if (i+1) + (16*j) < crossOverIndex: 
                value = hidden_layer_weights1[i][j] + float(random.randrange(-10,10)/50)
            else:
                value = hidden_layer_weights2[i][j] + float(random.randrange(-10,10)/50)
                
            rand = random.randint(0,19)
            if rand == 0:
                value = float(random.randrange(-100, 100))/100
            weights1[i][j] = value

    hidden_layer = network.W
    network = fully_connected(network, 4, activation='softmax')
    network = regression(network, optimizer='adam', learning_rate=1e-2, loss='mean_square', name='target')
    model = tflearn.DNN(network)

    crossOverIndex = random.randint(0,16)
    weights2 = numpy.zeros((4,4))
    for i in range(4):
        for j in range(4):
            if (i+1) + (16*j) < crossOverIndex: 
                value = parent_weights1[i][j] + float(random.randrange(-10,10)/50)
            else:
                value = parent_weights2[i][j] + float(random.randrange(-10,10)/50)
            rand = random.randint(0,19)
            if rand == 0:
                value = float(random.randrange(-100, 100))/100
            weights2[i][j] = value
    model.set_weights(network.W, weights2)
    model.set_weights(hidden_layer, weights1)
    

    return model, network.W, hidden_layer
    

In [24]:
def choose_parents(fitness_percentages):
    num = float(random.randrange(0,10000)/100)
    num2 = float(random.randrange(0,10000)/100)
   
    parent_index1 = 0
    parent_index2 = 0
    done = False
    done2 = False
    for i in range(25):
        num = num - fitness_percentages[i]
        num2 = num2 - fitness_percentages[i]
        if num < 0 and done == False:
            
            parent_index1 = i
            done = True
        if num2 < 0 and done2 == False:
            
            parent_index2 = i
            done2 = True
        if done and done2:
            return (parent_index1, parent_index2)
            
    
    return (parent_index1, parent_index2)
    

In [177]:
def new_population(best_models, best_networks, best_hiddenLayers, fitness_percentages):
    
    new_models = []
    new_networks = []
    new_hiddenLayers = []
    for i in range(75):
        #print(i)
        parent_indexes = choose_parents(fitness_percentages)
        parent1 = best_models[parent_indexes[0]]
        parent2 = best_models[parent_indexes[1]]
        networks1 = best_networks[parent_indexes[0]]
        networks2 = best_networks[parent_indexes[1]]
        hidden_layer1 = best_hiddenLayers[parent_indexes[0]]
        hidden_layer2 = best_hiddenLayers[parent_indexes[1]]
        
        child = create_children(parent1, parent2, networks1, networks2, hidden_layer1, hidden_layer2)
        model = child[0]
        network = child[1]
        hidden_layer = child[2]
        new_models.append(model)
        new_networks.append(network)
        new_hiddenLayers.append(hidden_layer)
    
    for i in range(25):
        new_models.append(best_models[i])
        new_networks.append(best_networks[i])
        new_hiddenLayers.append(best_hiddenLayers[i])
        
    return (new_models, new_networks, new_hiddenLayers)
        

In [445]:
def next_generation(models, networks, hidden_layers):
    
    total_scores = []
    bad_moves = []
    turns_in_corner = []
    all_scores = []
    
    for i in range(100):
        
        print(i)
        
        game = test_model(models[i])
        total_scores.append(game[0])
        bad_moves.append(game[1])
        turns_in_corner.append(game[2])
        all_scores.append(game[3])
        
    bestScore = 0
    best_index = 0
    for i in range(100):
        for j in range(10):
            if all_scores[i][j] > bestScore:
                bestScore = all_scores[i][j]
                best_index = i
        
    
    
    
    fitness = []
    for i in range(100):
        fitness_value = total_scores[i] + turns_in_corner[i]*10 - bad_moves[i]*3
        if best_index == i:
            fitness_value = fitness_value * 1.5
            print(fitness_value)
        fitness.append(fitness_value)
        
    sorted_models = sorted(zip(fitness,total_scores, models,networks,hidden_layers, all_scores), key=lambda pair: pair[0])
    fitness, total_scores, models, networks, hidden_layers, all_scores = zip(*sorted_models)
    print(total_scores)
    for i in range(99, 89, -1):
        print(models[i])
    
    
    total_value = 0
    
    
    for i in range(99,74,-1):
        total_value = total_value + total_scores[i]
        
    print(best_index)
    print("best score: " + str(bestScore))
        
    print("average score: " + str(total_value/250))
    best_models = []
    best_networks = []
    best_hiddenLayers = []
    
    
    total = 0
    for i in range(99, 74, -1):
        best_models.append(models[i])
        best_networks.append(networks[i])
        best_hiddenLayers.append(hidden_layers[i])
        total = total + fitness[i]
        
    best_fitness_percentages = []
    for i in range(99, 74, -1):
        fitness_value = float(fitness[i] / total) * 100
        best_fitness_percentages.append(fitness_value)
    
   
    print(best_fitness_percentages)
    
    
    return new_population(best_models, best_networks, best_hiddenLayers, best_fitness_percentages)
    

In [370]:
results = next_generation(models, networks, hidden_layers)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
(5956.0, 5752.0, 6612.0, 6164.0, 6956.0, 6772.0, 6472.0, 6660.0, 7008.0, 7892.0, 7220.0, 7036.0, 6856.0, 7268.0, 7792.0, 7488.0, 6804.0, 9192.0, 7708.0, 8584.0, 7668.0, 8004.0, 7732.0, 10060.0, 9352.0, 10620.0, 10292.0, 10968.0, 10800.0, 10192.0, 13144.0, 13340.0, 14500.0, 13620.0, 10184.0, 13020.0, 16924.0, 14124.0, 12056.0, 14660.0, 16980.0, 15480.0, 16124.0, 15276.0, 18372.0, 14876.0, 18504.0, 16420.0, 17928.0, 14940.0, 20748.0, 15972.0, 18736.0, 16112.0, 21048.0, 16984.0, 25544.0, 15960.0, 18280.0, 19060.0, 18248.0, 16728.0, 17596.0, 19644.0, 22428.0, 26256.0, 19052.0, 17988.0, 17824.0, 21132.0, 19044.0, 19612.0, 19288.0, 21692.0, 20604.0, 19968.0, 23212.0, 20028.0, 25912.0, 21748.0, 20588.0, 2088

In [529]:
results = next_generation(results[0], results[1], results[2])

0
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
72031.5
(5824.0, 7808.0, 10008.0, 11988.0, 11392.0, 17456.0, 16524.0, 16624.0, 15712.0, 18144.0, 15976.0, 14884.0, 18020.0, 18716.0, 16404.0, 16336.0, 18268.0, 18492.0, 19264.0, 17356.0, 17988.0, 19092.0, 18760.0, 21280.0, 22600.0, 19624.0, 20268.0, 18080.0, 21300.0, 18944.0, 20740.0, 21096.0, 21204.0, 23532.0, 20788.0, 23212.0, 23084.0, 19656.0, 22004.0, 22240.0, 21680.0, 22092.0, 22076.0, 20740.0, 24196.0, 21300.0, 24984.0, 24308.0, 22424.0, 23284.0, 23196.0, 22584.0, 27636.0, 22780.0, 23044.0, 22960.0, 23864.0, 22880.0, 24196.0, 25132.0, 22944.0, 26188.0, 24844.0, 23248.0, 24840.0, 24860.0, 24968.0, 23820.0, 23168.0, 25840.0, 27284.0, 27672.0, 25196.0, 24868.0, 32012.0, 25476.0, 26204.0, 25544.0,

In [518]:
results[0][75].get_weights(results[1][75])


array([[ 0.02999999, -1.8       , -0.3300001 ,  0.57      ],
       [-1.33      , -1.1399999 , -0.68      ,  0.6       ],
       [-0.08000002, -0.86999995,  0.59000015, -0.06999999],
       [ 0.23      ,  0.14999995, -0.05      ,  0.6100001 ]],
      dtype=float32)

In [537]:
game_board = numpy.zeros((4,4))
game_board[0][0] = 2


In [538]:
results[0][75].predict([translate_board(game_board)])[0]

array([0.04400798, 0.24263637, 0.3764308 , 0.3369248 ], dtype=float32)

In [330]:
def play_game(model):
    game_board = numpy.zeros((4,4))
    game_board = new_tiles(game_board)
    score = 0
    game_states = []
    game_moves = []
    gameOver = False
    isRepeating = False

    badMoves = 0
    turnsInCorner = 0

    move = 0

    legal_moves = [0,1,2,3]

    while gameOver == False:


        gameOver = (game_over(game_board))



        #game_states.append(game_board.copy())

        print(game_board.copy())
        print(score)
        #print(move)

        if isRepeating == False:

            legal_moves = [0,1,2,3]
            game_states.append(game_board.copy())
            game_moves.append(move)

            translatedBoard = translate_board(game_board)
            prediction = (model.predict([translatedBoard]))[0]
            move = 0
            largest_value = 0
            for i in range(4):
                if prediction[i] > largest_value:
                    move = i
                    largest_value = prediction[i]


        if (move > 3 or move < 0):

            move = random.randint(0,3)



        isRepeating = False

        if (move == 0):

            initial_board = game_board.copy()
            outputs = move_up(game_board,score)
            game_board = outputs[0]
            translated_board = translate_board(game_board)
            if translated_board[0][0] == 1:
                turnsInCorner += 1
            elif translated_board[0][3] == 1:
                turnsInCorner += 1
            elif translated_board[3][0] == 1:
                turnsInCorner += 1
            elif translated_board[3][3] == 1:
                turnsInCorner += 1
            score = outputs[1]
            isRepeating = (compare_boards(game_board, initial_board))


            if isRepeating:
                #gameOver = True
                legal_moves.remove(0)
                badMoves += 1
                translatedBoard = translate_board(game_board)
                prediction = (model.predict([translatedBoard]))[0]
                move = 1
                largest_value = 0
                for num in legal_moves:
                    if prediction[num] > largest_value:
                        move = num
                        largest_value = prediction[num]

                #move = random.randint(1,3)

        elif (move == 1):


            initial_board = game_board.copy()
            outputs = move_left(game_board,score)
            game_board = outputs[0]
            translated_board = translate_board(game_board)
            if translated_board[0][0] == 1:
                turnsInCorner += 1
            elif translated_board[0][3] == 1:
                turnsInCorner += 1
            elif translated_board[3][0] == 1:
                turnsInCorner += 1
            elif translated_board[3][3] == 1:
                turnsInCorner += 1
            score = outputs[1]
            isRepeating = (compare_boards(game_board, initial_board))


            if isRepeating:
                #gameOver = True
                legal_moves.remove(1)
                badMoves += 1
                translatedBoard = translate_board(game_board)
                prediction = (model.predict([translatedBoard]))[0]
                move = 0
                largest_value = 0
                for num in legal_moves:
                    if prediction[num] > largest_value:
                        move = num
                        largest_value = prediction[num]


        elif (move == 2):


            initial_board = game_board.copy()
            outputs = move_down(game_board,score)
            game_board = outputs[0]
            translated_board = translate_board(game_board)
            if translated_board[0][0] == 1:
                turnsInCorner += 1
            elif translated_board[0][3] == 1:
                turnsInCorner += 1
            elif translated_board[3][0] == 1:
                turnsInCorner += 1
            elif translated_board[3][3] == 1:
                turnsInCorner += 1
            score = outputs[1]
            isRepeating = (compare_boards(game_board, initial_board))


            if isRepeating:
                #gameOver = True
                legal_moves.remove(2)
                badMoves += 1
                translatedBoard = translate_board(game_board)
                prediction = (model.predict([translatedBoard]))[0]
                move = 0
                largest_value = 0
                for num in legal_moves:
                    if prediction[num] > largest_value:
                        move = num
                        largest_value = prediction[num]




        elif (move == 3):


                initial_board = game_board.copy()
                outputs = move_right(game_board,score)
                game_board = outputs[0]
                translated_board = translate_board(game_board)
                if translated_board[0][0] == 1:
                    turnsInCorner += 1
                elif translated_board[0][3] == 1:
                    turnsInCorner += 1
                elif translated_board[3][0] == 1:
                    turnsInCorner += 1
                elif translated_board[3][3] == 1:
                    turnsInCorner += 1
                score = outputs[1]
                isRepeating = (compare_boards(game_board, initial_board))


                if isRepeating:
                    #gameOver = True
                    legal_moves.remove(3)
                    badMoves += 1
                    translatedBoard = translate_board(game_board)
                    prediction = (model.predict([translatedBoard]))[0]
                    move = 0
                    largest_value = 0
                    for num in legal_moves:
                        if prediction[num] > largest_value:
                            move = num
                            largest_value = prediction[num]



            
            


        spotOpen = False
        for i in range (4):
            for j in range(4):
                if game_board[i][j] == 0:
                    spotOpen = True
        if spotOpen and isRepeating == False:
            game_board = new_tiles(game_board)
    print(badMoves, turnsInCorner)
    
    return score

In [540]:
play_game(results[0][75])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 2. 0. 0.]]
0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 2. 0. 0.]]
0.0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]
0.0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 2.]
 [4. 0. 0. 2.]]
0.0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 2. 0.]
 [4. 0. 0. 4.]]
4.0
[[0. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 0. 0.]
 [4. 0. 2. 4.]]
4.0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 4.]
 [4. 2. 2. 4.]]
4.0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 2.]
 [4. 2. 2. 8.]]
12.0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 2.]
 [4. 2. 2. 8.]]
12.0
[[0. 2. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 2.]
 [0. 4. 4. 8.]]
16.0
[[0. 0. 2. 0.]
 [0. 0. 0. 0.]
 [0. 2. 0. 2.]
 [0. 4. 4. 8.]]
16.0
[[0. 0. 2. 0.]
 [0. 0. 0. 0.]
 [0. 2. 2. 2.]
 [0. 4. 4. 8.]]
16.0
[[0. 0. 2. 0.]
 [0. 0. 2. 0.]
 [0. 2. 2. 2.]
 [0. 4. 4. 8.]]
16.0
[[0. 0. 2. 0.]
 [0. 0. 2. 0.]
 [0. 2. 4. 2.]
 [0. 4. 4. 8.]]
20.0
[[0. 0. 0. 4.]
 [0. 0. 0. 0.]
 [0. 2. 4. 2.]
 [0. 4. 8. 8.]]
32.0
[[0. 0. 2. 0.]
 [0.

[[  0.   0.   0.   4.]
 [  2.   0.   4.   8.]
 [  0.   0.  16.  32.]
 [  2.   4.   8. 128.]]
932.0
[[  0.   0.   0.   4.]
 [  4.   0.   4.   8.]
 [  2.   0.  16.  32.]
 [  2.   4.   8. 128.]]
932.0
[[  0.   0.   2.   4.]
 [  0.   0.   4.   8.]
 [  4.   0.  16.  32.]
 [  4.   4.   8. 128.]]
936.0
[[  0.   2.   2.   4.]
 [  0.   0.   4.   8.]
 [  0.   0.  16.  32.]
 [  8.   4.   8. 128.]]
944.0
[[  0.   0.   2.   4.]
 [  0.   0.   4.   8.]
 [  2.   2.  16.  32.]
 [  8.   4.   8. 128.]]
944.0
[[  0.   0.   2.   4.]
 [  0.   0.   4.   8.]
 [  2.   2.  16.  32.]
 [  8.   4.   8. 128.]]
944.0
[[  0.   0.   2.   4.]
 [  4.   0.   4.   8.]
 [  0.   4.  16.  32.]
 [  8.   4.   8. 128.]]
948.0
[[  0.   0.   2.   4.]
 [  0.   0.   4.   8.]
 [  4.   2.  16.  32.]
 [  8.   8.   8. 128.]]
956.0
[[  0.   0.   2.   4.]
 [  0.   0.   4.   8.]
 [  4.   2.  16.  32.]
 [  8.   8.   8. 128.]]
956.0
[[  0.   0.   2.   4.]
 [  0.   2.   4.   8.]
 [  4.   2.  16.  32.]
 [  0.   8.  16. 128.]]
972.0
[[  0.   0

[[  0.   2.   0.   4.]
 [  4.   4.   8.   8.]
 [  8.  16.  32.  64.]
 [  2.  32.  64. 128.]]
1688.0
[[  0.   2.   0.   4.]
 [  4.   4.   8.   8.]
 [  8.  16.  32.  64.]
 [  2.  32.  64. 128.]]
1688.0
[[  0.   0.   2.   4.]
 [  2.   0.   8.  16.]
 [  8.  16.  32.  64.]
 [  2.  32.  64. 128.]]
1712.0
[[  0.   0.   2.   4.]
 [  2.   0.   8.  16.]
 [  8.  16.  32.  64.]
 [  2.  32.  64. 128.]]
1712.0
[[  0.   4.   2.   4.]
 [  0.   2.   8.  16.]
 [  8.  16.  32.  64.]
 [  2.  32.  64. 128.]]
1712.0
[[  0.   4.   2.   4.]
 [  0.   2.   8.  16.]
 [  8.  16.  32.  64.]
 [  2.  32.  64. 128.]]
1712.0
[[  0.   4.   2.   4.]
 [  0.   2.   8.  16.]
 [  8.  16.  32.  64.]
 [  2.  32.  64. 128.]]
1712.0
[[  4.   2.   4.   0.]
 [  2.   8.  16.   4.]
 [  8.  16.  32.  64.]
 [  2.  32.  64. 128.]]
1712.0
[[  4.   2.   4.   0.]
 [  2.   8.  16.   4.]
 [  8.  16.  32.  64.]
 [  2.  32.  64. 128.]]
1712.0
[[  2.   4.   2.   4.]
 [  2.   8.  16.   4.]
 [  8.  16.  32.  64.]
 [  2.  32.  64. 128.]]
1712.0


1848.0